### ISSUE TITLE
add feature request

### ISSUE THREAD

**Issue by abe520** [Sergei-Korneev/Joplin-mobile-to-Obsidian-md#4]
add feature request
Insert the url, creation date and id of the joplin note to the end of the text
![image](https://user-images.githubusercontent.com/9929511/211088893-8fb62061-7df4-48ba-9698-8869dc91721a.png)

-----
````
--------------------------------------------
{{createdAt}}
{{url}}
{{id}}
````
-----

**Comment by Sergei-Korneev** [comment]
Hi. Just curious, do you use this script on a regular basis? 
Please compress your sample exported profile and attach it to your message. (I have lost my one from the test environment) 
I will see what  I can  do.

**Comment by abe520** [comment]
----
I tested this tool before, and it does lose some notes
![image](https://user-images.githubusercontent.com/9929511/211165416-faec3035-a7a4-4dbd-9eea-8adb940fabd8.png)

----
My joplin notes are converted from wiznote and I use [wiz2joplin](https://github.com/zrong/wiz2joplin).
Because of the huge joplin note files and joplin's poor sync functionality; I've been using both joplin and obsidian.
I want to keep the meta information (creation date, the url and ), but I can't find the right way to do it.

**Comment by abe520** [comment]
![image](https://user-images.githubusercontent.com/9929511/211165843-b2fd6689-1a86-41f1-bb47-ff54d1542c0b.png)

[JoplinProfileExport.zip](https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/files/10366989/JoplinProfileExport.zip)
[JoplinProfileExport2.zip](https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/files/10366990/JoplinProfileExport2.zip)

**Comment by Sergei-Korneev** [comment]
This script uses joplin note titles as md note filenames and sometimes , when title is too long or contains forbidden characters it may fail, yes. https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/issues/3
So you basically need to save url + creation date + id? OK, your request accepted.

**Comment by Sergei-Korneev** [comment]
Upd:
The issue turned to be more profound than I thought. :) And it requires much more time to fix. Of course this script cannot download files.
![image](https://user-images.githubusercontent.com/60899505/211182817-18b07e51-9dec-4e59-ac53-345f0a8cff1c.png)

**Comment by Sergei-Korneev** [comment]
Done. I just tested it on Linux.  https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/commit/e9ac40bcc2f7633029faa69f24f4ed99a2048c7d
Try new version. it won't download attachments though , you can use my plugin for that purpose. https://github.com/Sergei-Korneev/obsidian-local-images-plus

**Comment by abe520** [comment]
Thank you very much for your contribution.
Some notes still fail because the title is too long or contains forbidden characters.
Could you change it into a separate py file (add meta information) and make it work for joplin alone.
Then I can directly use joplin's export md or other.
![image](https://user-images.githubusercontent.com/9929511/211196562-56d1183e-04bf-4407-abc9-6c23c3d4af49.png)

**Comment by Sergei-Korneev** [comment]
Oh, I forgot that parent folder may not exist.  
That is why you see this error. I have made one more commit. Try again, please.
And about that separate py it is not quite clear what did you mean. I do not think it would be possible to add meta to already exported md files.

**Comment by abe520** [comment]
I mean:
Make an addmeta.py
Export JoplinProfileExport from joplin
Run Python3 addmeta.py
JoplinProfileExport import joplin
But it doesn't seem possible in the mobile version
![image](https://user-images.githubusercontent.com/9929511/211204624-5a3cbfcb-b973-4c6c-a971-bcca5a133810.png)
my notes are too messy
Thanks again

**Comment by Sergei-Korneev** [comment]
Yep, the error in     t=os.path.basename(findfiles(t, pathres)[0]) means the attachment mentioned in the note probably does not exist on disk.
I have moved the expression inside try-catch block, but it would be better if you send me compressed profile again including the note caused error  (clean all your private data first;) )
I will fix it tomorrow.

**Comment by abe520** [comment]
Contains Chinese characters that hinder your reading.
a:
![image](https://user-images.githubusercontent.com/9929511/211217485-22f8a21b-b350-41be-8ce7-6dc6d8c85681.png)
Notes with errors have been deleted in joplin-desktop.I don't need them anymore.

b:
![image](https://user-images.githubusercontent.com/9929511/211217520-511ea964-fce2-43ca-8990-9ec711e43dc0.png)
missing some pictures

**Comment by Sergei-Korneev** [comment]
Done .  You know what.... I started thinking of learning Chinese. :) 
![image](https://user-images.githubusercontent.com/60899505/211262278-9b481558-6397-4de7-a19e-ca4d72f619bb.png)

 You will need to run _pip install markdownify_ in your windows console first.

**Comment by Sergei-Korneev** [comment]
Sorry , one more finishing touch https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/commit/9ef2870a212708d9eea1e11670789231a25746bc

Some repeated images had multi extension like .jpg.jpg.jpg

redownload the script

**Comment by abe520** [comment]
Enough for normal use.
There's still a bit of a problem with headers to filenames, but it doesn't matter.
My truenas does not support pip, use docker to execute commands.
in linux
There is no error message when executing the command, but the file name will be garbled

in windows

Execute the command without any error prompt, the note will be lost


![image](https://user-images.githubusercontent.com/9929511/211329181-851bcd6a-5a05-4774-81b1-c1e445221312.png)
````
UTF-8
:
?
/
,
.
!
、
·
|
@

gbk code
：
？
／
，
。
！
＼
・
｜
＠

**Comment by Sergei-Korneev** [comment]
Yes, probably ntfs issue. On ext4/btrfs all is fine. I can see Chinese in all its glory!


![image](https://user-images.githubusercontent.com/60899505/211331413-34d928e2-c373-49a4-87aa-c0c3a847122c.png)

**Comment by abe520** [comment]
linux
![image](https://user-images.githubusercontent.com/9929511/211342425-0964deef-6dcf-4676-a283-b1e94c5e6430.png)

**Comment by Sergei-Korneev** [comment]
Yes, it just tries to tell you that something was not found and continues.

![image](https://user-images.githubusercontent.com/60899505/211353701-2d972b1c-df69-4d16-ae27-02eb78bd2dc5.png)
Now it is better i guess.

**Comment by abe520** [comment]
Thank you

**Comment by abe520** [comment]
The multi-level folder structure is broken: more than three levels of folders are modified into two-level folders
The same title under the same folder will be overwritten: the body text is different (page turning)

**Comment by Sergei-Korneev** [comment]
@abe520 are u using it for joplin mobile or desktop? as far as can remember the Joplin desktop is entirely different matter. The last time I used Joplin Mobile it alowed only one level folder structure:) And then I abandoned it for Obsidian .

**Comment by Sergei-Korneev** [comment]
Oh, I see. The mobile version has different db name. and what do you mean by "page turning"

**Comment by abe520** [comment]
I made a mistake.  My notes are saved in the desktop version.  There was a problem with synchronizing notes to the mobile version, so I used joplin-desktop to test.

**Comment by abe520** [comment]
Two notes with the same title will be overwritten and only one will be kept

**Comment by Sergei-Korneev** [comment]
Please open another issue like "Desktop version with multi-level folder structure" If you wish this script  to work with desktop version as well.
